---
title: "Vulnerability Assessment"
author: "Katherine Frazer"
date: "2024-10-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("setup.R")
```

# Crop Frequency

Let's read in the dataset.

```{r}
crop_freq <- read_excel("DataSets.xlsx", sheet = "Sheet1", 
    range = "A1:M13")

View(crop_freq)
```

As one can see, it isn't super workable at the moment. Let's use pivot_longer() to get it in a format we can use.

```{r}
crop_freq_tidy <- crop_freq %>%
  pivot_longer(cols = 1:13, 
               names_to = "County", 
               values_to = "CropType") %>%
  na.omit() #drop all rows with NA's

view(crop_freq_tidy)
```

```{r}
crop_freq_tidy <- crop_freq_tidy %>%
  group_by(CropType) %>% 
  summarise(Count = n())
```

```{r}
#NOTE: the gradient function came from this : https://stackoverflow.com/questions/48210231/creating-a-vertical-color-gradient-for-a-geom-bar-plot?noredirect=1&lq=1

#made adjustments to work with the function
df = crop_freq_tidy %>%
  mutate(x = CropType, y = Count) 

#refer to link
prepGradient <- function(x,y,spacing=max(y)/100){
  stopifnot(length(x)==length(y))
  df <- data.frame(x=x,y=y)
  newDf = data.frame(x=NULL,y=NULL,z=NULL)
  for (r in 1:nrow(df)){
    n <- floor(df[r,"y"]/spacing)
    for (s in c(1:n)){
      tmp <- data.frame(x=df[r,"x"],y=spacing,z=s*spacing)
      newDf <- rbind(newDf,tmp)
    }
    tmp <- data.frame(x=df[r,"x"],y=df[r,"y"]%%spacing,z=df[r,"y"])
    newDf <- rbind(newDf,tmp)
  }
  return(newDf)
}

df2 <- prepGradient(df$x,df$y)

ggplot(df2,aes(x=x,y=y,fill=z)) + 
  geom_bar(stat="identity") + 
  scale_fill_gradient2(low="#fbfb04", 
                       high="#e60000", 
                       mid="#ffaa00",
                       midpoint=median(df$y)) +   
  scale_y_continuous(breaks = seq(0, 13, 1)) +
  labs(title = "Frequency of Agricultural Products Produced",
       subtitle = "CO Counties of Interest: Adams, Cheyenne, Elbert, Kit Carson, Larimer, Lincoln, \nLogan, Morgan, Phillips, Sedgwick, Washington, Weld, and Yuma",
       caption = "Data Provided by Kelly, 2023",
       x = "Agricultural Product",
       y = "Number of Counties") +
  theme_classic() +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = "16"),
    plot.title.position = "plot",
    plot.subtitle = element_text(size = "10"),
    axis.title = element_text(face = "bold", size = "10"),
    axis.text.x = element_text(size = "5", angle = 22.5),
    axis.text.y = element_text(size = "5")
  ) +
  annotate(geom = "text", x = 6, y = 12.5, 
           label = "Corn is produced by \nall 13 counties.",
           size = 2.75) +
  geom_curve(aes(x = 4.3, xend = 3, y = 12.5, yend = 10.5),
             arrow = arrow(length = unit(0.2, "cm")),
             size = 0.5,
             curvature = 0.3)
  
ggsave(filename = "agprod.png", units = "in", height = 4, width = 6, dpi = 300, device = "tiff")
```

# Farming Jobs

Let's read in the dataset.

```{r}
jobs <- read_excel("DataSets.xlsx", sheet = "Sheet2", 
    range = "A1:B14")

View(jobs)
```

It looks workable already, so let's graph.

```{r, fig.width = 6}
jobs %>%
  ggplot(aes(x = County, y = AgWorkerPercentage)) +
  geom_col() +
  geom_text(aes(label = AgWorkerPercentage), 
            vjust = -0.3, 
            size = 2.75) +
  theme_classic() +
  expand_limits(y=c(0, 41)) +
  scale_y_continuous(breaks = seq(0, 40, 5)) +
  labs(title = "Percentage of Jobs within the Agricultural Sector",
       subtitle = "CO Counties of Interest: Adams, Cheyenne, Elbert, Kit Carson, Larimer, Lincoln, Logan, \nMorgan, Phillips, Sedgwick, Washington, Weld, and Yuma",
       caption = "Data provided by the Colorado Department of Local Affairs, 2022.",
       x = "County",
       y = "Percentage of Jobs") +
  theme(
    plot.title = element_text(face = "bold", size = "16"),
    plot.title.position = "plot",
    plot.subtitle = element_text(size = "10"),
    axis.title = element_text(face = "bold", size = "10"),
    axis.text.x = element_text(size = "5", angle = 22),
    axis.text.y = element_text(size = "5")
  ) +
  scale_fill_gradientn(waiver(), colours = c("red", "orange", "yellow"), breaks = c(10,20,30))
```

```{r}
#NOTE: the gradient function came from this : https://stackoverflow.com/questions/48210231/creating-a-vertical-color-gradient-for-a-geom-bar-plot?noredirect=1&lq=1

#made adjustments to work with the function
df = jobs %>%
  mutate(x = County, y = AgWorkerPercentage) 

#refer to link
prepGradient <- function(x,y,spacing=max(y)/100){
  stopifnot(length(x)==length(y))
  df <- data.frame(x=x,y=y)
  newDf = data.frame(x=NULL,y=NULL,z=NULL)
  for (r in 1:nrow(df)){
    n <- floor(df[r,"y"]/spacing)
    for (s in c(1:n)){
      tmp <- data.frame(x=df[r,"x"],y=spacing,z=s*spacing)
      newDf <- rbind(newDf,tmp)
    }
    tmp <- data.frame(x=df[r,"x"],y=df[r,"y"]%%spacing,z=df[r,"y"])
    newDf <- rbind(newDf,tmp)
  }
  return(newDf)
}

df2 <- prepGradient(df$x,df$y)

ggplot(df2,aes(x=x,y=y,fill=z)) + 
  geom_bar(stat="identity") + 
  scale_fill_gradient2(low="#fbfb04", 
                       high="#e60000", 
                       mid="#ffaa00",
                       midpoint=median(df$y))+

  # from here down is my code
  theme_classic() +
  expand_limits(y=c(0, 41)) +
  scale_y_continuous(breaks = seq(0, 40, 5)) +
  labs(title = "Jobs within the Agricultural Sector",
       subtitle = "CO Counties of Interest: Adams, Cheyenne, Elbert, Kit Carson, Larimer, Lincoln, \nLogan, Morgan, Phillips, Sedgwick, Washington, Weld, and Yuma",
       caption = "Data provided by the Colorado Department of Local Affairs, 2022.",
       x = "County",
       y = "Percentage of Jobs") +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = "16"),
    plot.title.position = "plot",
    plot.subtitle = element_text(size = "10"),
    axis.title = element_text(face = "bold", size = "10"),
    axis.text.x = element_text(size = "5", angle = 22),
    axis.text.y = element_text(size = "5")
  ) +
  #the following is not elegant, but I spent way too long trying to figure out how to not do what I am about to do, and needed to just finish this
  annotate(geom = "text", x = 1, y = (0.55+1.5),
           label = "0.55", size = 2.75) +
  annotate(geom = "text", x = 2, y = (35.38+1.5),
           label = "35.38", size = 2.75) +
  annotate(geom = "text", x = 3, y = (12.38+1.5),
           label = "12.38", size = 2.75) +
  annotate(geom = "text", x = 4, y = (21.13+1.5),
           label = "21.13", size = 2.75) +
  annotate(geom = "text", x = 5, y = (1.03+1.5),
           label = "1.03", size = 2.75) +
  annotate(geom = "text", x = 6, y = (18.25+1.5),
           label = "18.25", size = 2.75) +
  annotate(geom = "text", x = 7, y = (11.19+1.5),
           label = "11.19", size = 2.75) +
  annotate(geom = "text", x = 8, y = (9.36+1.5),
           label = "9.36", size = 2.75) +
  annotate(geom = "text", x = 9, y = (26.72+1.5),
           label = "26.72", size = 2.75) +
  annotate(geom = "text", x = 10, y = (30.1+1.5),
           label = "30.1", size = 2.75) +
  annotate(geom = "text", x = 11, y = (38.43+1.5),
           label = "38.43", size = 2.75) +
  annotate(geom = "text", x = 12, y = (4.02+1.5),
           label = "4.02", size = 2.75) +
  annotate(geom = "text", x = 13, y = (29.29+1.5),
           label = "29.29", size = 2.75)

ggsave(filename = "agjobs.png", units = "in", height = 4, width = 6, dpi = 300, device = "tiff")
```
